### ISSUE TITLE
You can glitch out the wall (Crash)

### ISSUE THREAD

**Issue by vindognz** [SolVince-Games/PyTetris#2]
To replicate:

Take a piece, rotate it into its longest state, then press it against the wall. Rotate the piece once, then move it into the wall, and rotate in the same frame. Crashed.

To fix:

Make a grid outside the grid and shove the piece back into the game if it enters that prolly.

**Comment by solman252** [comment]
the problem stems from the fact that collision is detected in the frame previous to the current frame. When you do the glitch, rotation is done first thing on a frame, then movement is done without the collision being retested.

**Comment by solman252** [comment]
all we would need to do is move the collision to be right before the movement, and another thing we could do is if a player still manages to go out of bounds, reset the piece to start pos
